"""initial schema

Revision ID: c56fa7b34395
Revises: 
Create Date: 2025-06-17 21:57:31.890083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56fa7b34395'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.create_index(op.f('ix_call_logs_tracking_id'), 'call_logs', ['tracking_id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    op.create_index(op.f('ix_packages_tracking_id'), 'packages', ['tracking_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_tracking_id'), table_name='packages')
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_call_logs_tracking_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    op.drop_table('call_logs')
    # ### end Alembic commands ###
